install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          

version: 1.0.{build}
build:
  project: FluentSharp.sln
  verbosity: minimal
